-- =============================================================================
-- Migration 006: service_subpackages parent index + seed offer-system catalog
-- =============================================================================

-- Step 1: add missing index on service_subpackages
create index if not exists service_subpackages_parent
  on public.service_subpackages (parent_package_id, sort_order)
  where archived = false;

-- Step 2: upsert service_packages from catalog
insert into public.service_packages
  (service_type, code, display_names, description, default_one_time_amount, default_monthly_amount, setup_fee, sort_order, is_active)
values
  ('web_dev', 'web-dev-landing', '{"en": "Landing Page", "el": "Landing Page"}'::jsonb, 'Στοχευμένη Landing Page για conversions, copywriting για leads, responsive design, φόρμα επικοινωνίας ή εκδήλωσης ενδιαφέροντος, γρήγορη φόρτωση και καθαρό UX, βασική παρακολούθηση conversions, παράδοση έτοιμη για διαφήμιση, 2 κύκλοι διορθώσεων. + Hosting 120€/έτος + ΦΠΑ.', 300, 0, 0, 10, true),
  ('web_dev', 'web-dev-professional', '{"en": "Επαγγελματική Ιστοσελίδα", "el": "Επαγγελματική Ιστοσελίδα"}'::jsonb, 'Φιλικό σε κινητά, 5 στατικές σελίδες, custom & responsive design, φόρμα επικοινωνίας, χάρτης Google, βασικό SEO, 2 κύκλοι διορθώσεων. + Hosting 120€/έτος + ΦΠΑ.', 500, 0, 0, 20, true),
  ('web_dev', 'web-dev-custom', '{"en": "Custom", "el": "Custom"}'::jsonb, 'Προσαρμοσμένη τιμή ανάλογα με το project και τις ανάγκες που ζητάει ο πελάτης.', 0, 0, 0, 30, true),
  ('local_seo', 'local-seo-local', '{"en": "Local Plan", "el": "Local Plan"}'::jsonb, 'Βασικό πακέτο Local SEO με όλα τα βασικά features. Τιμή ανά μήνα.', 0, 250, 0, 10, true),
  ('local_seo', 'local-seo-growth', '{"en": "Growth Plan", "el": "Growth Plan"}'::jsonb, 'Προχωρημένο πακέτο Local SEO με περιεχόμενο marketing και προσωπική στρατηγική. Τιμή ανά μήνα.', 0, 349, 0, 20, true),
  ('local_seo', 'local-seo-premium', '{"en": "Premium Plan", "el": "Premium Plan"}'::jsonb, 'Πλήρες πακέτο Local SEO με διαχείριση πολλαπλών καναλιών. Τιμή ανά μήνα.', 0, 650, 0, 30, true),
  ('web_seo', 'web-seo-basic', '{"en": "Βασικό", "el": "Βασικό"}'::jsonb, 'Περισσότερες επισκέψεις από Google, καλύτερες θέσεις στις αναζητήσεις, περισσότερα leads και επαφές, αυξημένη online παρουσία, περισσότερες πωλήσεις, καλύτερη αξιοπιστία, περισσότερη εμπιστοσύνη. Τιμή ανά μήνα.', 0, 350, 0, 10, true),
  ('web_seo', 'web-seo-eshop', '{"en": "Eshop", "el": "Eshop"}'::jsonb, 'Όλα τα Βασικό + σταθερή ανάπτυξη, βελτιστοποίηση product pages, περισσότερες παραγγελίες, καλύτερη conversion rate, περισσότερα reviews, αυξημένη brand awareness, πλεονέκτημα ανταγωνισμού. Τιμή ανά μήνα.', 0, 650, 0, 20, true),
  ('web_seo', 'web-seo-enterprise', '{"en": "Enterprise", "el": "Enterprise"}'::jsonb, 'Όλα τα Eshop + Premium link building, στρατηγική περιεχομένου, International SEO, συνεχής βελτιστοποίηση, προσωπικός SEO consultant, dedicated account manager, προτεραιότητα support. Custom τιμή / μήνα.', 0, 0, 0, 30, true),
  ('ai_seo', 'ai-seo', '{"en": "AI SEO", "el": "AI SEO"}'::jsonb, 'ΑΙ περιεχόμενο τύπου ChatGPT & Gemini, έξυπνη εύρεση λέξεων που φέρνουν πελάτες, περιεχόμενο που απαντά στις ερωτήσεις των πελατών σου, ανάλυση ανταγωνισμού με ΑΙ, βελτιστοποίηση περιεχομένου για ΑΙ Search αποτελέσματα (Google AI Overviews). Τιμή ανά μήνα.', 0, 400, 0, 10, true),
  ('ai_seo', 'ai-seo-premium', '{"en": "AI SEO Premium", "el": "AI SEO Premium"}'::jsonb, 'Όλα τα AI SEO + AI Chatbot που συλλέγει leads και απαντά έξυπνα, εκπαίδευση ΑΙ με δεδομένα της επιχείρησής σου, συνεχής προσαρμογή σε αλλαγές αλγορίθμων, μηνιαία ανασκόπηση στρατηγικής ΑΙ. Τιμή ανά μήνα.', 0, 600, 0, 20, true),
  ('social_media', 'social-basiko-full', '{"en": "Βασικό – Λήψεις & Επεξεργασία (5 videos / μήνα)", "el": "Βασικό – Λήψεις & Επεξεργασία (5 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos (humorous / educational / presentations), εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, επαγγελματικό συνεργείο με εξοπλισμό (κάμερες, φώτα, μικρόφωνα), σενάριο ανά video, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, monthly reporting και προσωπικός σύμβουλος. 5 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 600, 0, 10, true),
  ('social_media', 'social-epaggelmatiko-full', '{"en": "Επαγγελματικό – Λήψεις & Επεξεργασία (10 videos / μήνα)", "el": "Επαγγελματικό – Λήψεις & Επεξεργασία (10 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos (humorous / educational / presentations), εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, επαγγελματικό συνεργείο με εξοπλισμό (κάμερες, φώτα, μικρόφωνα), σενάριο ανά video, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, monthly reporting και προσωπικός σύμβουλος. 10 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 1200, 0, 20, true),
  ('social_media', 'social-premium-full', '{"en": "Premium – Λήψεις & Επεξεργασία (15 videos / μήνα)", "el": "Premium – Λήψεις & Επεξεργασία (15 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos (humorous / educational / presentations), εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, επαγγελματικό συνεργείο με εξοπλισμό (κάμερες, φώτα, μικρόφωνα), σενάριο ανά video, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, monthly reporting και προσωπικός σύμβουλος. 15 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 1800, 0, 30, true),
  ('social_media', 'social-basiko-edit', '{"en": "Βασικό – Μόνο Επεξεργασία (5 videos / μήνα)", "el": "Βασικό – Μόνο Επεξεργασία (5 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos με υλικό που στέλνει ο πελάτης, εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, βελτιστοποίηση performance, monthly reporting και προσωπικός σύμβουλος. 5 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 450, 0, 40, true),
  ('social_media', 'social-epaggelmatiko-edit', '{"en": "Επαγγελματικό – Μόνο Επεξεργασία (10 videos / μήνα)", "el": "Επαγγελματικό – Μόνο Επεξεργασία (10 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos με υλικό που στέλνει ο πελάτης, εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, βελτιστοποίηση performance, monthly reporting και προσωπικός σύμβουλος. 10 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 810, 0, 50, true),
  ('social_media', 'social-premium-edit', '{"en": "Premium – Μόνο Επεξεργασία (15 videos / μήνα)", "el": "Premium – Μόνο Επεξεργασία (15 videos / μήνα)"}'::jsonb, 'Πλήρως custom videos με υλικό που στέλνει ο πελάτης, εξατομικευμένο marketing plan, στρατηγική βασισμένη σε trends, high-quality επεξεργασία ήχου/εικόνας, custom υπότιτλοι & special effects, μηνιαία έρευνα concept, βελτιστοποίηση performance, monthly reporting και προσωπικός σύμβουλος. 15 videos / μήνα. Τιμή ανά μήνα. ΦΠΑ δεν περιλαμβάνεται.', 0, 1170, 0, 60, true),
  ('ads', 'ads-google-ads', '{"en": "Services google ads", "el": "Services google ads"}'::jsonb, 'Διαχείριση και βελτιστοποίηση Google Ads.', 0, 150, 0, 10, true),
  ('ads', 'ads-eshop-google-ads', '{"en": "Eshop google ads", "el": "Eshop google ads"}'::jsonb, 'Google Ads για e-shop.', 0, 300, 0, 20, true),
  ('ads', 'ads-meta-ads', '{"en": "Meta Ads", "el": "Meta Ads"}'::jsonb, 'Διαφήμιση Meta (Facebook / Instagram).', 0, 150, 0, 30, true)
on conflict (service_type, code) do update set
  display_names            = excluded.display_names,
  description              = excluded.description,
  default_one_time_amount  = excluded.default_one_time_amount,
  default_monthly_amount   = excluded.default_monthly_amount,
  sort_order               = excluded.sort_order;

-- Step 3: upsert service_subpackages from catalog
insert into public.service_subpackages
  (parent_package_id, code, display_names, description, price, sort_order, is_active)
  select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-booking-stripe', '{"en": "Booking με Stripe", "el": "Booking με Stripe"}'::jsonb, 'Σύστημα κρατήσεων με online πληρωμές μέσω Stripe. Εφάπαξ.', 500, 10, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-diglosso', '{"en": "Δίγλωσσο Website", "el": "Δίγλωσσο Website"}'::jsonb, 'Ελληνικά + Αγγλικά περιεχόμενο και ρύθμιση. Εφάπαξ.', 200, 20, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-ai-chatbot-setup', '{"en": "AI Chat Bot (Setup)", "el": "AI Chat Bot (Setup)"}'::jsonb, 'Setup AI chatbot στο website. Εφάπαξ.', 200, 30, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-ai-chatbot-monthly', '{"en": "AI Chat Bot (Συνδρομή)", "el": "AI Chat Bot (Συνδρομή)"}'::jsonb, 'Συνδρομή AI chatbot. / μήνα.', 100, 40, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-hosting-simple', '{"en": "Hosting απλό site", "el": "Hosting απλό site"}'::jsonb, 'Φιλοξενία απλού WordPress website. / έτος.', 120, 50, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-hosting-eshop', '{"en": "Hosting e-shop", "el": "Hosting e-shop"}'::jsonb, 'Φιλοξενία WordPress e-shop. / έτος.', 180, 60, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-migration-small', '{"en": "Migration μικρό site", "el": "Migration μικρό site"}'::jsonb, 'Μεταφορά μικρού ή απλού site σε δικό μας hosting. Εφάπαξ (150–200€).', 175, 70, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-migration-large', '{"en": "Migration μεγάλο site", "el": "Migration μεγάλο site"}'::jsonb, 'Μεταφορά μεγάλου ή απαιτητικού site. Εφάπαξ (500–600€).', 550, 80, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-email-marketing', '{"en": "Email Marketing", "el": "Email Marketing"}'::jsonb, 'Setup και βασική στρατηγική email marketing. Εφάπαξ.', 200, 90, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-newsletter-setup', '{"en": "Newsletter setup", "el": "Newsletter setup"}'::jsonb, 'Φόρμα newsletter και σύνδεση με πλατφόρμα. Εφάπαξ.', 150, 100, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-support-simple-monthly', '{"en": "Μηνιαίο Support απλό site", "el": "Μηνιαίο Support απλό site"}'::jsonb, 'Τεχνική υποστήριξη απλών σελίδων. / μήνα.', 60, 110, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-landing'), 'extra-support-eshop-monthly', '{"en": "Μηνιαίο Support e-shop", "el": "Μηνιαίο Support e-shop"}'::jsonb, 'Τεχνική υποστήριξη e-shop. / μήνα (150–200€).', 175, 120, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-booking-stripe', '{"en": "Booking με Stripe", "el": "Booking με Stripe"}'::jsonb, 'Σύστημα κρατήσεων με online πληρωμές μέσω Stripe. Εφάπαξ.', 500, 10, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-diglosso', '{"en": "Δίγλωσσο Website", "el": "Δίγλωσσο Website"}'::jsonb, 'Ελληνικά + Αγγλικά περιεχόμενο και ρύθμιση. Εφάπαξ.', 200, 20, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-ai-chatbot-setup', '{"en": "AI Chat Bot (Setup)", "el": "AI Chat Bot (Setup)"}'::jsonb, 'Setup AI chatbot στο website. Εφάπαξ.', 200, 30, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-ai-chatbot-monthly', '{"en": "AI Chat Bot (Συνδρομή)", "el": "AI Chat Bot (Συνδρομή)"}'::jsonb, 'Συνδρομή AI chatbot. / μήνα.', 100, 40, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-hosting-simple', '{"en": "Hosting απλό site", "el": "Hosting απλό site"}'::jsonb, 'Φιλοξενία απλού WordPress website. / έτος.', 120, 50, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-hosting-eshop', '{"en": "Hosting e-shop", "el": "Hosting e-shop"}'::jsonb, 'Φιλοξενία WordPress e-shop. / έτος.', 180, 60, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-migration-small', '{"en": "Migration μικρό site", "el": "Migration μικρό site"}'::jsonb, 'Μεταφορά μικρού ή απλού site σε δικό μας hosting. Εφάπαξ (150–200€).', 175, 70, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-migration-large', '{"en": "Migration μεγάλο site", "el": "Migration μεγάλο site"}'::jsonb, 'Μεταφορά μεγάλου ή απαιτητικού site. Εφάπαξ (500–600€).', 550, 80, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-email-marketing', '{"en": "Email Marketing", "el": "Email Marketing"}'::jsonb, 'Setup και βασική στρατηγική email marketing. Εφάπαξ.', 200, 90, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-newsletter-setup', '{"en": "Newsletter setup", "el": "Newsletter setup"}'::jsonb, 'Φόρμα newsletter και σύνδεση με πλατφόρμα. Εφάπαξ.', 150, 100, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-support-simple-monthly', '{"en": "Μηνιαίο Support απλό site", "el": "Μηνιαίο Support απλό site"}'::jsonb, 'Τεχνική υποστήριξη απλών σελίδων. / μήνα.', 60, 110, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-professional'), 'extra-support-eshop-monthly', '{"en": "Μηνιαίο Support e-shop", "el": "Μηνιαίο Support e-shop"}'::jsonb, 'Τεχνική υποστήριξη e-shop. / μήνα (150–200€).', 175, 120, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-booking-stripe', '{"en": "Booking με Stripe", "el": "Booking με Stripe"}'::jsonb, 'Σύστημα κρατήσεων με online πληρωμές μέσω Stripe. Εφάπαξ.', 500, 10, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-diglosso', '{"en": "Δίγλωσσο Website", "el": "Δίγλωσσο Website"}'::jsonb, 'Ελληνικά + Αγγλικά περιεχόμενο και ρύθμιση. Εφάπαξ.', 200, 20, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-ai-chatbot-setup', '{"en": "AI Chat Bot (Setup)", "el": "AI Chat Bot (Setup)"}'::jsonb, 'Setup AI chatbot στο website. Εφάπαξ.', 200, 30, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-ai-chatbot-monthly', '{"en": "AI Chat Bot (Συνδρομή)", "el": "AI Chat Bot (Συνδρομή)"}'::jsonb, 'Συνδρομή AI chatbot. / μήνα.', 100, 40, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-hosting-simple', '{"en": "Hosting απλό site", "el": "Hosting απλό site"}'::jsonb, 'Φιλοξενία απλού WordPress website. / έτος.', 120, 50, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-hosting-eshop', '{"en": "Hosting e-shop", "el": "Hosting e-shop"}'::jsonb, 'Φιλοξενία WordPress e-shop. / έτος.', 180, 60, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-migration-small', '{"en": "Migration μικρό site", "el": "Migration μικρό site"}'::jsonb, 'Μεταφορά μικρού ή απλού site σε δικό μας hosting. Εφάπαξ (150–200€).', 175, 70, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-migration-large', '{"en": "Migration μεγάλο site", "el": "Migration μεγάλο site"}'::jsonb, 'Μεταφορά μεγάλου ή απαιτητικού site. Εφάπαξ (500–600€).', 550, 80, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-email-marketing', '{"en": "Email Marketing", "el": "Email Marketing"}'::jsonb, 'Setup και βασική στρατηγική email marketing. Εφάπαξ.', 200, 90, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-newsletter-setup', '{"en": "Newsletter setup", "el": "Newsletter setup"}'::jsonb, 'Φόρμα newsletter και σύνδεση με πλατφόρμα. Εφάπαξ.', 150, 100, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-support-simple-monthly', '{"en": "Μηνιαίο Support απλό site", "el": "Μηνιαίο Support απλό site"}'::jsonb, 'Τεχνική υποστήριξη απλών σελίδων. / μήνα.', 60, 110, true
  union all select (select id from public.service_packages where service_type = 'web_dev' and code = 'web-dev-custom'), 'extra-support-eshop-monthly', '{"en": "Μηνιαίο Support e-shop", "el": "Μηνιαίο Support e-shop"}'::jsonb, 'Τεχνική υποστήριξη e-shop. / μήνα (150–200€).', 175, 120, true
  union all select (select id from public.service_packages where service_type = 'local_seo' and code = 'local-seo-local'), 'installation-local', '{"en": "Κόστος Εγκατάστασης", "el": "Κόστος Εγκατάστασης"}'::jsonb, 'Εφάπαξ κόστος εγκατάστασης', 300, 10, true
  union all select (select id from public.service_packages where service_type = 'local_seo' and code = 'local-seo-growth'), 'installation-growth', '{"en": "Κόστος Εγκατάστασης", "el": "Κόστος Εγκατάστασης"}'::jsonb, 'Εφάπαξ κόστος εγκατάστασης', 400, 10, true
  union all select (select id from public.service_packages where service_type = 'local_seo' and code = 'local-seo-premium'), 'installation-premium', '{"en": "Κόστος Εγκατάστασης", "el": "Κόστος Εγκατάστασης"}'::jsonb, 'Εφάπαξ κόστος εγκατάστασης', 550, 10, true
on conflict (parent_package_id, code) do update set
  display_names = excluded.display_names,
  description   = excluded.description,
  price         = excluded.price,
  sort_order    = excluded.sort_order;

-- Step 4: archive old placeholder packages seeded by migration 024
-- (generic codes: basic/standard/premium/starter/business/enterprise)
-- These are superseded by the catalog-keyed rows above.
update public.service_packages
  set archived = true
  where code in ('basic', 'standard', 'premium', 'starter', 'business', 'enterprise')
    and archived = false;
