-- Payment reminders were still firing for newly-onboarded deals whose payment
-- row was created on/after its own due_date (accounting back-dating the record
-- so historical periods match the client's real invoice date). Live audit on
-- 2026-07-01 caught 4 payment_overdue sends this morning going to deals created
-- yesterday (still status='pending' at 06:00 UTC, marked paid by accounting
-- around 08:00 UTC — clients received an "overdue" reminder for money they had
-- literally just paid). Add two extra guards on top of the stage-gate:
--   1. dp.paid_at IS NULL          — belt-and-suspenders vs status
--   2. dp.created_at::date < dp.start_date — skip back-dated onboarding rows
-- Normal recurring rows are generated by ensure_recurring_payments() ahead of
-- their due_date, so the second guard leaves the legitimate reminder path intact.

create or replace function public.enqueue_payment_reminders()
returns int
language plpgsql security definer set search_path = public as $$
declare
  r record;
  tkey text;
  dkey text;
  prefix text;
  created int := 0;
begin
  for r in
    select dp.id as payment_id, dp.service_type, dp.amount_gross, dp.start_date as due_date,
           dp.deal_id, d.code as deal_code, c.name as client_name, c.email as to_email
      from public.deal_payments dp
      join public.deals d on d.id = dp.deal_id
                         and d.archived = false
                         and d.suppress_payment_reminders = false
      join public.pipeline_stages ps
                        on ps.id = d.accounting_stage_id
                       and ps.board = 'accounting_onboarding'
                       and ps.code in ('invoice_issued','awaiting_payment',
                                       'partial_payment','paid_in_full','on_hold')
      join public.clients c on c.id = d.client_id
     where dp.status in ('pending', 'overdue')
       and dp.paid_at is null
       and dp.created_at::date < dp.start_date
       and c.email is not null and c.email <> ''
       and dp.start_date in (current_date + 7, current_date - 1, current_date - 7)
  loop
    if r.due_date = current_date + 7 then
      tkey := 'payment_due_soon'; prefix := 'pay_soon';
    elsif r.due_date = current_date - 1 then
      tkey := 'payment_overdue'; prefix := 'pay_overdue';
    else
      tkey := 'payment_final_notice'; prefix := 'pay_final';
    end if;

    dkey := prefix || ':' || r.payment_id;

    if exists (select 1 from public.email_log where dedupe_key = dkey and status = 'sent') then
      continue;
    end if;
    if exists (select 1 from public.email_outbox where dedupe_key = dkey and status in ('pending','sending','sent')) then
      continue;
    end if;

    insert into public.email_outbox (identity, to_email, template_key, data, dedupe_key)
    values ('accounting', r.to_email, tkey,
            jsonb_build_object('code', r.deal_code, 'client_name', r.client_name,
                               'service_type', r.service_type, 'amount_gross', r.amount_gross,
                               'due_date', to_char(r.due_date, 'DD/MM/YYYY'), 'deal_id', r.deal_id),
            dkey);
    created := created + 1;
  end loop;
  return created;
end $$;

-- Re-enable the accounting department mailer (paused at 09:46 UTC while the
-- root cause of today's misfires was being investigated).
update public.email_automation_settings
   set enabled = true, updated_at = now()
 where key = 'dept_accounting';

-- ROLLBACK:
--   -- 1. Revert the function to the stage-gate-only version (drop both guards):
--   create or replace function public.enqueue_payment_reminders() returns int
--   language plpgsql security definer set search_path = public as $$
--   declare r record; tkey text; dkey text; prefix text; created int := 0;
--   begin
--     for r in
--       select dp.id as payment_id, dp.service_type, dp.amount_gross,
--              dp.start_date as due_date, dp.deal_id, d.code as deal_code,
--              c.name as client_name, c.email as to_email
--         from public.deal_payments dp
--         join public.deals d on d.id = dp.deal_id
--                            and d.archived = false
--                            and d.suppress_payment_reminders = false
--         join public.pipeline_stages ps
--                           on ps.id = d.accounting_stage_id
--                          and ps.board = 'accounting_onboarding'
--                          and ps.code in ('invoice_issued','awaiting_payment',
--                                          'partial_payment','paid_in_full','on_hold')
--         join public.clients c on c.id = d.client_id
--        where dp.status in ('pending','overdue')
--          and c.email is not null and c.email <> ''
--          and dp.start_date in (current_date + 7, current_date - 1, current_date - 7)
--     loop
--       if r.due_date = current_date + 7 then tkey := 'payment_due_soon'; prefix := 'pay_soon';
--       elsif r.due_date = current_date - 1 then tkey := 'payment_overdue'; prefix := 'pay_overdue';
--       else tkey := 'payment_final_notice'; prefix := 'pay_final'; end if;
--       dkey := prefix || ':' || r.payment_id;
--       if exists (select 1 from public.email_log where dedupe_key = dkey and status = 'sent') then continue; end if;
--       if exists (select 1 from public.email_outbox where dedupe_key = dkey and status in ('pending','sending','sent')) then continue; end if;
--       insert into public.email_outbox (identity, to_email, template_key, data, dedupe_key)
--       values ('accounting', r.to_email, tkey,
--               jsonb_build_object('code', r.deal_code, 'client_name', r.client_name,
--                                  'service_type', r.service_type, 'amount_gross', r.amount_gross,
--                                  'due_date', to_char(r.due_date, 'DD/MM/YYYY'), 'deal_id', r.deal_id),
--               dkey);
--       created := created + 1;
--     end loop;
--     return created;
--   end $$;
--   -- 2. Pause the department mailer again if the rollback is because we're
--   --    unsure the guard is correct:
--   update public.email_automation_settings set enabled = false, updated_at = now()
--    where key = 'dept_accounting';
